---
- name: create swap file
  shell: >
    fallocate -l 2G /swapfile && \
    chmod 600 /swapfile && \
    mkswap /swapfile && \
    swapon /swapfile && \
    echo "/swapfile   swap    swap    sw  0   0" | tee -a /etc/fstab && \
    free -m
  ignore_errors: yes

- name: import specific linux distribution tasks
  import_tasks: "CentOS.yml"
  when: ansible_distribution == "CentOS"

- name: create remote install dir
  file:
    path: "{{ install_dir_remote }}"
    state: directory

- name: copy install files
  copy:
    src: "{{ install_dir_local }}"
    dest: "{{ install_dir_remote }}"

- name: unarchive rpm installation zip file
  unarchive:
    src: "{{ install_dir_remote }}/{{ install_zip_file }}"
    dest: "{{ install_dir_remote }}"
    remote_src: yes

- name: oracle xe silent install
  shell: sudo rpm -ivh {{ install_dir_remote }}/Disk1/oracle-xe-11.2.0-1.0.x86_64.rpm > {{ oracle_xe_install_log_file }}
  args:
    warn: false

- name: oracle xe configure
  command: /etc/init.d/oracle-xe configure responseFile={{ oracle_xe_response_file }}

- name: copy bash_profile to user oracle
  copy:
    src: "{{ install_dir_local }}.bash_profile"
    dest: "/u01/app/oracle/"
    owner: "oracle"
    group: "dba"

- name: create scripts directory on /u01/app/oracle/
  file:
    path: "/u01/app/oracle/scripts"
    state: directory
    owner: oracle
    group: dba

- name: copy SQL file
  copy:
    src: "objects.sql"
    dest: "/u01/app/oracle/scripts/objects.sql"
    owner: "oracle"
    group: "dba"

- name: execute SQL Script
  shell: sudo su - oracle -c "sqlplus system/oracle@xe @/u01/app/oracle/scripts/objects.sql"
  args:
    warn: false #during the logon, oracle user has a bash_profile to load oracle env parameters
